### ISSUE TITLE
Error importing AggregatedClustersCosts

### ISSUE THREAD

**Issue by Carloszapata91** [spotinst/spotinst-sdk-python#136]
In my python file, I have this:

```python
from spotinst_sdk2.models.ocean.aws import AggregatedClusterCosts
``` 

...and I am getting the next error:

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from spotinst_sdk2.models.ocean.aws import AggregatedClusterCosts
ImportError: cannot import name 'AggregatedClusterCosts' from 'spotinst_sdk2.models.ocean.aws' (C:\Users\daz_R\AppData\Local\Programs\Python\Python38\lib\site-packages\spotinst_sdk2\models\ocean\aws\__init__.py)

What can I do to fix that?

Thanks in advance

**Comment by anuragsharma-123** [comment]
Hello @Carloszapata91 - Can you please check if you are using latest version of the SDK. I tried with below sample code and was successfully able to obtain the cost -

from spotinst_sdk2 import SpotinstSession
from spotinst_sdk2.models.ocean.aws import AggregatedClusterCosts
session = SpotinstSession(auth_token='<your-token>', account_id='<your-account>')
client = session.client("ocean_aws", log_level="debug")
cost = AggregatedClusterCosts(end_time='2023-07-12T12:00:00Z', start_time='2023-07-10T12:00:00Z')
print(client.get_aggregated_cluster_costs(ocean_id = 'o-406c70a4', aggregated_cluster_costs = cost))

**Comment by anuragsharma-123** [comment]
@Carloszapata91 - were you able to try the sample code above? Shall I consider as closed?

**Comment by Carloszapata91** [comment]
Hi  @anuragsharma-123, that worked for me.... thanks
