### ISSUE TITLE
"Unable to import module 'lambda_function': No module named 'spotinst_sdk2'"

### ISSUE THREAD

**Issue by carlzapa** [spotinst/spotinst-sdk-python#141]
Hi.
I am creating an AWS lambda function using python  and I need to use the spotinst_sdk2 library.  I tried using the 2.1.35 version  and also the current version (2.1.41), but I always receive the same error message: 

Response
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'spotinst_sdk2'",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

It looks like it is not able to import the spotinst_sdk2 module ..

What can I do?

Thanks in advance

**Comment by anuragsharma-123** [comment]
Hi @carlzapa,

1) spotinst-sdk2 is not part of default python installation, therefore, to use it in lambda function a deployment package is to be created. It is straightforward process. Here are the instructions from AWS.

https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-dependencies

2) All the dependencies and lambda function should be at same level inside zip file for upload. 
3) Another important thing to note, default timeout of lambda functions is 3 second, where most of our REST calls will it timeout. Recommending to increase it to 1 minute in the "Configuration" tab.

Let me know if it works for you or not.

**Comment by carlzapa** [comment]
Hi @anuragsharma-123.
It worked for me... I just needed to use 3.8 python and I also needed to increase the timeout because it takes eleven minutes to end the api calls.

Thanks
