### ISSUE TITLE
Missing agent repos

### ISSUE THREAD

**Issue by jayvdb** [spotinst/spotinst-sdk-python#65]
https://pypi.org/project/spotinst-agent/ and https://pypi.org/project/spotinst-agent-beta/ refer to repository https://github.com/spotinst/spotinst-spectrum-agent , however that repo doesnt exist.

**Comment by anuragsharma-123** [comment]
This is an old ticket. Checked that the The repository https://github.com/spotinst/spotinst-spectrum-agent exist now. Requesting submitter to open a ticket if they see any other issue in the SDK.
