### ISSUE TITLE
`setup.py` imports `requests` and `PyYAML`

### ISSUE THREAD

**Issue by vkhromov** [spotinst/spotinst-sdk-python#7]
https://github.com/spotinst/spotinst-sdk-python/blob/master/setup.py#L7:
```
import spotinst_sdk
```
https://github.com/spotinst/spotinst-sdk-python/blob/master/spotinst_sdk/__init__.py#L5:
```
import requests
import yaml
```

**Comment by danieldop** [comment]
closed along with [issue9](https://github.com/spotinst/spotinst-sdk-python/issues/6)
