### ISSUE TITLE
GCP Elastigroup examples

### ISSUE THREAD

**Issue by bassplay3r** [spotinst/spotinst-sdk-python#76]
Would like to use this for GCP but I'm not seeing an example and most things look specific to AWS. 
Are  Azure and GCP supported?

**Comment by anuragsharma-123** [comment]
Hello,

Yes, both Azure and GCP elastigroups are supported. Please check example at below link for GCP.

https://github.com/spotinst/spotinst-sdk-python/tree/v2/docs/examples#gcp-elastigroup

Please raise issue if you are unable to use. Closing the ticket for now.

Anurag
