### ISSUE TITLE
ModuleNotFoundError: No module named 'spotinst_sdk2.clients.setup'

### ISSUE THREAD

**Issue by ShubhamKhairnar** [spotinst/spotinst-sdk-python#85]
Hello Team,

Just after release of version 2.1.8, we got following error in one of our implementation:
**ModuleNotFoundError: No module named 'spotinst_sdk2.clients.setup'**

But, when we switched back to 2.1.7, it all worked fine.

I think there is some bug in version 2.1.8 and seems to be at:
**spotinst_sdk2/__init__.py", line 12**

Please look into it.

Thanks,
Shubham K

**Comment by SHxKM** [comment]
Hi,

Sorry about this. Please update to to `>=2.1.10` - this issue is fixed from that version on.
